spring.application.name=api

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Security
api.security.token.secret=${JWT_SECRET}
api.security.cors.secret=${CORS_SECRET}

# Document
storage.upload-dir=/app/assets

# Admin user

api.user.login=${USER_LOGIN}
api.user.password=${USER_PASSWORD}
api.user.name=${USER_NAME}

#spring.jpa.show-sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.orm.jdbc.bind=TRACE
#logging.level.org.springframework.transaction=TRACE